### PR TITLE
Print errors to stderr instead of stdout.

### LINKED ISSUE #20: Errors should go to stderr
Most command line tools send `--help` and `--version` output to stdout, but send parsing failures to stderr. `argh` now sends both of these 'early exits' to stdout.

### PR DESCRIPTION
**Pull request by m-ou-se**
Fixes #20

### CODE REVIEW

**Comment by ofadieiev** [comment]
@m-ou-se Hi! I just wonder is it possible to add some tests for this (positive, negative)?

**Comment by fadeevab** [comment]
@m-ou-se Once you signed you have to comment with the following:

@googlebot I signed it!

(Let's see whether it helps right now)

**Comment by m-ou-se** [comment]
Eh, it requires me to log in with a Google account and read several pages of questionable legalese.

(You really expect everybody to register with Google (reading to over 60 pages of terms of service), give up personal data to create an account, and then read another few pages of this CLA and agree to it all?)

I guess I should've read the `CONTRIBUTING.md` first.

Never mind then.

My changes are published as open source here: https://github.com/m-ou-se/argh/tree/stderr Feel free to take them from there.

**Comment by fadeevab** [comment]
@m-ou-se Hey, be careful that I'm not a maintainer even, just wait until @benbrittain appears here :) I am just contributor and also signed all this shit

**Comment by benbrittain** [comment]
@m-ou-se I'm sorry about this. On a personal level I also have some very mixed feelings on CLAs. I appreciate this stance.

Unfortunately, I also think you are right about this issue... but I can't take your changes. :frowning_face:

**Comment by m-ou-se** [comment]
> I can't take your changes.

I think point 7 of the [CLA](https://cla.developers.google.com/about/google-individual) means you still can.

> :frowning_face:

I feel your pain. This was one of the reasons I quit Google a few years ago.

**Pull request closed without merging**
