### PR TITLE
allow alphanumeric strings in `long` attribute

### PR DESCRIPTION
**Pull request by theli-ua**
Argh already allows usage of field names such as `ac97` but not if
specified in `long` attribute

### CODE REVIEW

**Review by erickt — APPROVED** [review]

**Comment by erickt** [comment]
@theli-ua - would you be able to fix the clippy lint?

**Comment by theli-ua** [comment]
@erickt I could fix it its just that its not even in any files I touched :D

**Comment by erickt** [comment]
@theli-ua oh, sorry about that! It looks like your build is green now. Could you sign the [CLA](https://cla.developers.google.com/clas)? I'll be able to merge it in afterwards.

**Comment by theli-ua** [comment]
funny enough that was originally submitted as romanton@google.com ...
either way I signed it now

**Comment by erickt** [comment]
Thanks!

**Pull request merged**
